#--------------------12------------------------------------------------------------
library(ISLR)
library(class)
library(MASS)
#-------------------(a)------------------------
Power=function(){print(2^3)}
#-------------------(b)------------------------
Power2=function(x,a)
{print(x^a)}
Power2(3,8)
#------------------(c)-------------------------
Power2(10,3)
Power2(8,17)
Power2(131,3)
#------------------(d)-------------------------
Power3=function(x,a){
result=x^a
return(result)
}
Power3(2,3)
#------------------(e)--------------------------
Figure=plot(1:10,Power3(1:10,2),xlab="X-axis",ylab="Y-axis",log="xy",col="black",cex=3,type="p",main="X^2 plot in log scale",lwd="5")
#------------------(f)--------------------------
PlotPower=function(x,a){
plot(x,x^a,cex=2,col="red")
}
PlotPower(1:10,3)
#---------------------------------------------------------------------------------
